name = "gentle-boat-9b6b"
main = "src/index.js"
compatibility_date = "2023-10-30"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["* * * * *"] # * * * * * = run every minute
